### PR TITLE
Fixed compilation with PHP 5.6

### PR DESCRIPTION
**Pull request by davidsteinsland**
Tested against PHP 5.6.3 and 5.5.20.

### CODE REVIEW

**Comment by Qix-** [comment]
Yes please :D

**Comment by tototoshi** [comment]
:+1:

**Comment by Qix-** [comment]
Where are the maintainers to review this? I have clients that need to install Runkit and I don't feel comfortable telling them they need to use a patch from a non-official account... This should be a no brainer.

**Comment by tmuras** [comment]
@Qix- I'd suggest to contact @zenovich directly and offer to pay him for that review and merge.

**Comment by Qix-** [comment]
@tmuras Thanks for the snarky and useless comment :+1:

**Comment by nijel** [comment]
Any plans to add PHP 7 support as well?

**Comment by tony2001** [comment]
I seriously doubt all this stuff is going to work with PHP7.
Most likely it'll require some serious modifications.

**Pull request merged**
