### PR TITLE
Fixed compiling against PHP 5.6.0RC4

### LINKED ISSUE #69: Broken build against 5.6.0RC1
Because of (from UPGRADING.INTERNALS):

    l. Removal of IS_CONSTANT_ARRAY and IS_CONSTANT_INDEX hack
    
    These two #defines disappeared. Instead we have now IS_CONSTANT_AST which
    covers also the functionality IS_CONSTANT_ARRAY bid and furthermore the
    hack for marking zvals as constant index with IS_CONSTANT_INDEX is now
    superfluous and so removed.
    Please note that IS_CONSTANT_AST now has the same value than
    IS_CONSTANT_ARRAY had.

### PR DESCRIPTION
**Pull request by adrianguenter**
Fixes #69

### CODE REVIEW

**Comment by davidcasey** [comment]
+1

**Comment by Qix-** [comment]
Yeah this needs to get added :P Can we please push this forward?

**Comment by rotatingJazz** [comment]
+1000 :+1:

**Comment by davidsteinsland** [comment]
As there were some merge conflicts and BC related stuff here, I created #73 instead.

**Comment by zenovich** [comment]
Done in #73

**Pull request closed without merging**
